name: Deploy UserImage Management App

on:
  push:
    branches:
      - master  # Trigger the workflow on push to the master branch
  workflow_dispatch:  # Allow manual trigger of the workflow from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to the latest stable version

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Updated to the latest stable version
        with:
          node-version: '14'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build
